/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Chess;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author FP
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbutton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jbutton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jbutton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(8, 8));

        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton1);

        jbutton2.setBackground(new java.awt.Color(0, 0, 0));
        jbutton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbutton2.setForeground(new java.awt.Color(255, 255, 255));
        jbutton2.setMaximumSize(new java.awt.Dimension(50, 50));
        jbutton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jbutton2);

        jButton3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton66.setBackground(new java.awt.Color(0, 0, 0));
        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton66);

        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton65);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton6.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton7.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton8.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton9.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton9);

        jButton10.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton10.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton10);

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton11.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton11);

        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton67);

        jButton69.setBackground(new java.awt.Color(0, 0, 0));
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton69);

        jButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton68);

        jbutton12.setMaximumSize(new java.awt.Dimension(50, 50));
        jbutton12.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jbutton12);

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton13.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton13);

        jbutton14.setMaximumSize(new java.awt.Dimension(50, 50));
        jbutton14.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jbutton14);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton15.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton15);

        jButton16.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton16.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton16);

        jButton70.setBackground(new java.awt.Color(0, 0, 0));
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton70);

        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton71);

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton17.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton17);

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton18.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton18);

        jButton19.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton19.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton19);

        jButton20.setBackground(new java.awt.Color(0, 0, 0));
        jButton20.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton20.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton20);

        jButton21.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton21.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton21);

        jButton22.setBackground(new java.awt.Color(0, 0, 0));
        jButton22.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton22.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton22);

        jButton23.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton23.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton23);

        jButton72.setBackground(new java.awt.Color(0, 0, 0));
        jButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton72);

        jButton24.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton24.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton24);

        jButton25.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton25.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton25);

        jButton26.setBackground(new java.awt.Color(0, 0, 0));
        jButton26.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton26.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton26);

        jButton27.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton27.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton27);

        jButton28.setBackground(new java.awt.Color(0, 0, 0));
        jButton28.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton28.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton28);

        jButton29.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton29.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton29);

        jButton30.setBackground(new java.awt.Color(0, 0, 0));
        jButton30.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton30.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton30);

        jButton31.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton31.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton31);

        jButton32.setBackground(new java.awt.Color(0, 0, 0));
        jButton32.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton32.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton32);

        jButton33.setBackground(new java.awt.Color(0, 0, 0));
        jButton33.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton33.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton33);

        jButton34.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton34.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton34);

        jButton35.setBackground(new java.awt.Color(0, 0, 0));
        jButton35.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton35.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton35);

        jButton36.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton36.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton36);

        jButton37.setBackground(new java.awt.Color(0, 0, 0));
        jButton37.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton37.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton37);

        jButton38.setText("C");
        jButton38.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton38.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton38);

        jButton39.setBackground(new java.awt.Color(0, 0, 0));
        jButton39.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton39.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton39);

        jButton40.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton40.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton40);

        jButton41.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton41.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton41);

        jButton42.setBackground(new java.awt.Color(0, 0, 0));
        jButton42.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton42.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton42);

        jButton43.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton43.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton43);

        jButton44.setBackground(new java.awt.Color(0, 0, 0));
        jButton44.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton44.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton44);

        jButton45.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton45.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton45);

        jButton46.setBackground(new java.awt.Color(0, 0, 0));
        jButton46.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton46.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton46);

        jButton47.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton47.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton47);

        jButton48.setBackground(new java.awt.Color(0, 0, 0));
        jButton48.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton48.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton48);

        jButton49.setBackground(new java.awt.Color(0, 0, 0));
        jButton49.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton49.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton49);

        jButton50.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton50.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton50);

        jButton51.setBackground(new java.awt.Color(0, 0, 0));
        jButton51.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton51.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton51);

        jButton52.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton52.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton52);

        jButton53.setBackground(new java.awt.Color(0, 0, 0));
        jButton53.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton53.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton53);

        jButton54.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton54.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton54);

        jButton55.setBackground(new java.awt.Color(0, 0, 0));
        jButton55.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton55.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
            }
        });
        jPanel1.add(jButton55);

        jButton56.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton56.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculaPosicion(evt);
                metodo(evt);
            }
        });
        jPanel1.add(jButton56);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculaPosicion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculaPosicion
        // TODO add your handling code here:
        JButton button = (JButton) evt.getSource();
        JPanel panel = (JPanel) button.getParent();
        GridLayout gl = (GridLayout) button.getParent().getLayout();
        
        int col, row;
        int pos = -1;
        Component[] components = panel.getComponents();
        for(int i = 0; i < components.length; i++){
            if(button == components[i]){
                pos = i;
                break;
            }
        
        }
        switch (pos / 8) {
            case 0:
                row = 0;
                col = pos;
                break;
            case 1:
                row = 1;
                col = pos - 8;
                break;
            case 2:
                row = 2;
                col = pos - 16;
                break;
            case 3:
                row = 3;
                col = pos - 24;
                break;
            case 4:
                row = 4;
                col = pos - 32;
                break;
            case 5:
                row = 5;
                col = pos - 40;
                break;
            case 6:
                row = 6;
                col = pos - 48;
                break;
            case 7:
                row = 7;
                col = pos - 56;
                break;
            default:
                row = -1;
                col = -1;
                break;
        }
        if(caballo.movimiento(row,col)){
            JFrame frame = new JFrame();
            JPanel pane = new JPanel(new BorderLayout());
            frame.setContentPane(pane);
            JButton b = new JButton("OK");
            pane.add(b,BorderLayout.SOUTH);
            JLabel label = new JLabel("MOVIMIENTO CORRECTO");
            pane.add(label, BorderLayout.NORTH);
            b.addActionListener(e -> {
                frame.dispose();
            });
            frame.setVisible(true);
            frame.setSize(250, 250);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
        }
        else{
            JFrame frame = new JFrame();
            JPanel pane = new JPanel(new BorderLayout());
            frame.setContentPane(pane);
            JButton b = new JButton("OK");
            pane.add(b,BorderLayout.SOUTH);
            JLabel label = new JLabel("MOVIMIENTO INCORRECTO");
            pane.add(label, BorderLayout.NORTH);
            b.addActionListener(e -> {
                frame.dispose();
            });
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            frame.setVisible(true);
            frame.setSize(250, 250);
        }
        
        
    }//GEN-LAST:event_calculaPosicion

    private void metodo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodo
        // TODO add your handling code here:
    }//GEN-LAST:event_metodo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Interfaz().setVisible(true);
            }
        });
    }
    //aqui metes la posicion del caballo.
    //lo meto en la posicion : columna 5 y fila 5;
    private Caballo caballo = new Caballo("blanco", 5,5);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutton12;
    private javax.swing.JButton jbutton14;
    private javax.swing.JButton jbutton2;
    // End of variables declaration//GEN-END:variables
}
