/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author Usuario
 */
public class Calc extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        opPorcentaje = new javax.swing.JButton();
        opCe = new javax.swing.JButton();
        opC = new javax.swing.JButton();
        opDel = new javax.swing.JButton();
        opUnoEntre = new javax.swing.JButton();
        opXcuadrado = new javax.swing.JButton();
        opSqrt = new javax.swing.JButton();
        opdiv = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        opMult = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        opResta = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        opMas = new javax.swing.JButton();
        opmasmenos = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        opcoma = new javax.swing.JButton();
        opIgual = new javax.swing.JButton();
        pantalla = new javax.swing.JTextField();
        modo = new javax.swing.JLabel();
        memoria = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(6, 4));

        opPorcentaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opPorcentaje.setText("%");
        opPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPorcentajeActionPerformed(evt);
            }
        });
        jPanel1.add(opPorcentaje);

        opCe.setText("CE");
        opCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCeActionPerformed(evt);
            }
        });
        jPanel1.add(opCe);

        opC.setText("C");
        opC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCActionPerformed(evt);
            }
        });
        jPanel1.add(opC);

        opDel.setText("DEL");
        opDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDelActionPerformed(evt);
            }
        });
        jPanel1.add(opDel);

        opUnoEntre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opUnoEntre.setText("1/x");
        opUnoEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opUnoEntreActionPerformed(evt);
            }
        });
        jPanel1.add(opUnoEntre);

        opXcuadrado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        opXcuadrado.setText("x²");
        opXcuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opXcuadradoActionPerformed(evt);
            }
        });
        jPanel1.add(opXcuadrado);

        opSqrt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        opSqrt.setText("√");
        opSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSqrtActionPerformed(evt);
            }
        });
        jPanel1.add(opSqrt);

        opdiv.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        opdiv.setText("÷");
        opdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opdivActionPerformed(evt);
            }
        });
        jPanel1.add(opdiv);

        num7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        jPanel1.add(num7);

        num8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        jPanel1.add(num8);

        num9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        jPanel1.add(num9);

        opMult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opMult.setText("X");
        opMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMultActionPerformed(evt);
            }
        });
        jPanel1.add(opMult);

        num4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        jPanel1.add(num4);

        num5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        jPanel1.add(num5);

        num6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        jPanel1.add(num6);

        opResta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        opResta.setText("-");
        opResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opRestaActionPerformed(evt);
            }
        });
        jPanel1.add(opResta);

        num1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        jPanel1.add(num1);

        num2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        jPanel1.add(num2);

        num3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        jPanel1.add(num3);

        opMas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        opMas.setText("+");
        opMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMasActionPerformed(evt);
            }
        });
        jPanel1.add(opMas);

        opmasmenos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opmasmenos.setText("+/-");
        opmasmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmasmenosActionPerformed(evt);
            }
        });
        jPanel1.add(opmasmenos);

        num0.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        jPanel1.add(num0);

        opcoma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        opcoma.setText(",");
        opcoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcomaActionPerformed(evt);
            }
        });
        jPanel1.add(opcoma);

        opIgual.setBackground(new java.awt.Color(0, 153, 255));
        opIgual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        opIgual.setForeground(new java.awt.Color(255, 255, 255));
        opIgual.setText("=");
        opIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opIgualActionPerformed(evt);
            }
        });
        jPanel1.add(opIgual);

        pantalla.setEditable(false);
        pantalla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaActionPerformed(evt);
            }
        });

        modo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modo.setText("Estándar");

        memoria.setEditable(false);
        memoria.setForeground(new java.awt.Color(102, 102, 102));
        memoria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        memoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
            .addComponent(pantalla)
            .addComponent(memoria)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPorcentajeActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().length() > 0) {
            double num= Double.parseDouble(pantalla.getText());
            double resultado = num/100;
            pantalla.setText(String.valueOf(resultado));
            memoria.setText(String.valueOf(resultado));
        }
    }//GEN-LAST:event_opPorcentajeActionPerformed

    private void opCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCeActionPerformed
        // TODO add your handling code here:
        pantalla.setText("");
    }//GEN-LAST:event_opCeActionPerformed

    private void opCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCActionPerformed
        // TODO add your handling code here:
        pantalla.setText("");
        memoria.setText("");
    }//GEN-LAST:event_opCActionPerformed

    private void opDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDelActionPerformed
        if (pantalla.getText().length()>0) {
            pantalla.setText(pantalla.getText().substring(0, pantalla.getText().length() -1 ));
        }
        
        
    }//GEN-LAST:event_opDelActionPerformed

    private void opUnoEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opUnoEntreActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().length() > 0) {
            double num= Double.parseDouble(pantalla.getText());
            double resultado = 1/num;
            pantalla.setText(String.valueOf(resultado));
            memoria.setText(String.valueOf(resultado));
        }
    }//GEN-LAST:event_opUnoEntreActionPerformed

    private void opXcuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opXcuadradoActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().length() > 0) {
            double num= Double.parseDouble(pantalla.getText());
            double resultado = Math.pow(num,2);
            pantalla.setText(String.valueOf(resultado));
            memoria.setText(String.valueOf(resultado));
        }
        
    }//GEN-LAST:event_opXcuadradoActionPerformed

    private void opSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSqrtActionPerformed
       
        if (pantalla.getText().length() > 0) {
            double num= Double.parseDouble(pantalla.getText());
            double resultado = Math.sqrt(num);
            pantalla.setText(String.valueOf(resultado));
            memoria.setText(String.valueOf(resultado));
        }
    }//GEN-LAST:event_opSqrtActionPerformed

    private void opdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opdivActionPerformed
        if (pantalla.getText().length() > 0) {
        memoria.setText(pantalla.getText() + "/");
        signo = true;
        }
    }//GEN-LAST:event_opdivActionPerformed

    private void opMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMultActionPerformed
        if (pantalla.getText().length() > 0) {
        memoria.setText(pantalla.getText() + "*");
        signo = true;
        }
    }//GEN-LAST:event_opMultActionPerformed

    private void opRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opRestaActionPerformed
       if (pantalla.getText().length() > 0) {
        memoria.setText(pantalla.getText() + "-");
        signo = true;
       }
    }//GEN-LAST:event_opRestaActionPerformed

    private void opMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMasActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().length() > 0) {
            memoria.setText(pantalla.getText() + "+");
            signo = true;
        }
        

    }//GEN-LAST:event_opMasActionPerformed

    private void opmasmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmasmenosActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().length() > 0) {
            double num= Double.parseDouble(pantalla.getText());
            double resultado = num*-1;
            pantalla.setText(String.valueOf(resultado));
            memoria.setText(String.valueOf(resultado));
        }
    }//GEN-LAST:event_opmasmenosActionPerformed

    private void opcomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcomaActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().length() > 0 && cuentaComas(pantalla.getText())) {
            pantalla.setText(pantalla.getText() + ".");
        }
    }//GEN-LAST:event_opcomaActionPerformed

    private void opIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opIgualActionPerformed
        // TODO add your handling code here:
        if(memoria.getText().length() > 0){
            double num1, num2, result;
            switch(memoria.getText().charAt(memoria.getText().length() - 1)){
                
                case '+':
                    num1 = Double.parseDouble(memoria.getText().substring(0, memoria.getText().length() - 1));
                    num2 = Double.parseDouble(pantalla.getText());
                    result = num1 + num2;
                    pantalla.setText(String.valueOf(result));
                    break;
                case '-':
                    num1 = Double.parseDouble(memoria.getText().substring(0, memoria.getText().length() - 1));
                    num2 = Double.parseDouble(pantalla.getText());
                    result = num1 - num2;
                    pantalla.setText(String.valueOf(result));
                    
                    break;
                case '*':
                    num1 = Double.parseDouble(memoria.getText().substring(0, memoria.getText().length() - 1));
                    num2 = Double.parseDouble(pantalla.getText());
                    result = num1 * num2;
                    pantalla.setText(String.valueOf(result));
                    
                    break;
                case '/':
                    num1 = Double.parseDouble(memoria.getText().substring(0, memoria.getText().length() - 1));
                    num2 = Double.parseDouble(pantalla.getText());
                    result = num1 / num2;
                    pantalla.setText(String.valueOf(result));
                    
                    break;
                    
                default:
                    
                    
            }
        }
        
    }//GEN-LAST:event_opIgualActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        if (signo == true) {
            pantalla.setText("9");
            signo = false;
        }
        else{
            pantalla.setText(pantalla.getText() + "9");
        }
    }//GEN-LAST:event_num9ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        if (signo == true) {
            pantalla.setText("8");
            signo = false;
        }
        else
        pantalla.setText(pantalla.getText() + "8");
    }//GEN-LAST:event_num8ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        if (signo == true) {
            pantalla.setText("7");
            signo = false;
        }
        else
        pantalla.setText(pantalla.getText() + "7");
    }//GEN-LAST:event_num7ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        if (signo == true) {
            pantalla.setText("6");
            signo = false;
        }
        else
        pantalla.setText(pantalla.getText() + "6");
    }//GEN-LAST:event_num6ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        if (signo == true) {
            pantalla.setText("5");
            signo = false;
        }
        else
        pantalla.setText(pantalla.getText() + "5");
    }//GEN-LAST:event_num5ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        if (signo == true) {
            pantalla.setText("4");
            signo = false;
        }
        else
        pantalla.setText(pantalla.getText() + "4");
    }//GEN-LAST:event_num4ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        if (signo == true) {
            pantalla.setText("3");
            signo = false;
        }
        else
        pantalla.setText(pantalla.getText() + "3");
    }//GEN-LAST:event_num3ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        if (signo == true) {
            pantalla.setText("2");
            signo = false;
        }
        else
        pantalla.setText(pantalla.getText() + "2");
    }//GEN-LAST:event_num2ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        if (signo == true) {
            pantalla.setText("1");
            signo = false;
        }
        else
        pantalla.setText(pantalla.getText() + "1");
    }//GEN-LAST:event_num1ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
        if (signo == true) {
            pantalla.setText("0");
            signo = false;
        }
        else
        pantalla.setText(pantalla.getText() + "0");
    }//GEN-LAST:event_num0ActionPerformed

    private void pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallaActionPerformed

    private void memoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }   
    //Método que devuelve false si hay ya una coma en el String
    //Lo uso para controlar el numero de comas que pueda poner el usuario
    private boolean cuentaComas(String s){
        for(int i = 0; i < s.length(); i++){
            if(s.charAt(i) == '.'){               
                 return false;
            }
        }
        return true;
    }
    //Variable para controlar si el ultimo caracter escrito es un signo
    private boolean signo = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField memoria;
    private javax.swing.JLabel modo;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton opC;
    private javax.swing.JButton opCe;
    private javax.swing.JButton opDel;
    private javax.swing.JButton opIgual;
    private javax.swing.JButton opMas;
    private javax.swing.JButton opMult;
    private javax.swing.JButton opPorcentaje;
    private javax.swing.JButton opResta;
    private javax.swing.JButton opSqrt;
    private javax.swing.JButton opUnoEntre;
    private javax.swing.JButton opXcuadrado;
    private javax.swing.JButton opcoma;
    private javax.swing.JButton opdiv;
    private javax.swing.JButton opmasmenos;
    private javax.swing.JTextField pantalla;
    // End of variables declaration//GEN-END:variables
}
